version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: phrase-sharing
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: phrase-sharing-php
    restart: always
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html

volumes:
  db_data:
